fix function prototypes
../drivers/input/touchscreen/st/fts_lib/ftsIO.c:85:22: error: a function declaration without a prototype is deprecated in
 all versions of C [-Werror,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void
../drivers/input/touchscreen/st/fts_lib/ftsIO.c:93:29: error: a function declaration without a prototype is deprecated in
 all versions of C [-Werror,-Wstrict-prototypes]
struct i2c_client *getClient()
                            ^
                             void
../drivers/input/touchscreen/st/fts_lib/ftsTime.c:95:16: error: a function declaration without a prototype is deprecated
in all versions of C [-Werror,-Wstrict-prototypes]
char *timestamp()
               ^
../drivers/input/touchscreen/fts_touch/fts_lib/ftsIO.c:128:29: error: a function declaration without a prototype is depre
cated in all versions of C [-Werror,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1288:34: error: a function declaration
without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:88:40: error: a function declarati
on without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/scan/dispatcher/src/wlan_extscan_api.c:103:27: error: a function
declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
wlan_extscan_global_deinit()
                          ^
                           void
../drivers/usb/pd/pd_engine.c:2175:26: error: a function declaration without a prototype is deprecated in all versions of
 C [-Werror,-Wstrict-prototypes]
static void parse_cmdline()
                         ^
                          void