pd_engine: Add void argument to old-style zero prototype function
clang-15 complains:
drivers/usb/pd/pd_engine.c:2175:26: error: a function declaration
without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
static void parse_cmdline()
                         ^
                          void
1 error generated.

Change-Id: I0e449b9646b5f3b96baf4b8078d1d3bb25a433af